config/routes.rb
Tagger::Application.routes.draw do

  resources :tags, :only => [:index] do
    member do
      put 'increment'
    end
  end

  root :to => 'tags#index'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :hits, :numericality => true

  scope :order_by_rank, lambda { |order|
    order = 'desc' unless ['asc', 'desc'].include?(order.downcase)
    select('*, ROUND((hits/(SELECT MAX(hits) FROM tags))*10) rank').order("rank #{order.upcase}")
  }

  class <<self
    def maximum_hits
      maximum('hits') || 0
    end
  end

  # we're hitting 'rank' every time, but this should be performance hog since it uses query cache for quering maximum
  def as_json(options = {})
    { :id => self.id, :name => self.name, :hits => self.hits, :rank => self.rank }
  end

  def hit!
    increment(:hits)
    save
  end

  def rank
    self.class.maximum_hits.zero? ? 0 : ((hits.to_f / self.class.maximum_hits.to_f) * 10).round
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  respond_to :html, :json
  before_filter :find_tag, :only => [:increment]

  def index
    respond_with(@tags = Tag.order_by_rank('desc'))
  end

  def increment
    @tag.hit!
    respond_with(@tag, :location => tags_url)
  end

  protected

  def find_tag
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tagger</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tags/_tag.html.erb
<%= link_to tag.name, increment_tag_path(tag), :method => :put %> (<%= tag.hits %>) &nbsp;

app/views/tags/index.html.erb
<h1>Tags</h1>

<%= render @tags %>